Fix/revpi 1846/adjust connect to platform driver
RevolutionPi/piControl pull request #52
Opened 2022-02-04 15:37 UTC by linosanfilippo-kunbus

2022-02-16 11:07 UTC, l1k commented on revpi_core.c
> -	/* reset GPIO direction */
Please retain this code comment, otherwise it is totally unclear what you're doing in `deinit_sniff_pins()`.

2022-02-16 11:20 UTC, l1k requested changes
_

2022-02-26 09:08 UTC, l1k approved these changes

2022-02-28 10:52 UTC, iluminat23 approved these changes

2022-02-28 12:36 UTC, merged