Revpi 2647/use serdev highlevel functions aio
RevolutionPi/piControl pull request #78
Opened 2022-11-14 17:23 UTC by linosanfilippo-kunbus

2022-11-20 06:45 UTC, l1k commented
About commit f1ac37cb7e1c ("piControl: use pibridge_req_io() to send AIO config messages"):

Functionally, the commit is fine. I still have a recommendation: I would amend the definitions of `SAioConfig` and `SAioInConfig` in IoProtocol.h to drop the `uHeader` and `i8uCrc` members.

Next, drop all the code in `piAIOComm_Config()` to populate the `uHeader` fields and calculate the `i8uCrc`. All of that is just dead code because you let `pibridge_req_io()` construct the header and crc. It's confusing to retain that code even though it no longer has any use.

These changes will allow you to define `AIO_CONFIG_DATA1/2/3_LEN` as `sizeof(SAioConfig)` or `sizeof(SAioInConfig)`, respectively, leading to (IMO) clearer code. Alternatively, you could forgo those macro definitions entirely and just use `sizeof()` directly in the `pibridge_req_io()` calls. If you feel that it adds value to document those packet sizes (it probably does), add the information to IoProtocol.h.

2022-11-20 06:49 UTC, l1k requested changes

2022-11-20 08:43 UTC, l1k commented on piAIOComm.c
> +		return 4; // unknown device
Good idea to add this check and thus make it possible to reduce indentation below by 2 tabs.

2022-11-20 12:15 UTC, l1k commented
Ugh, I've realized only now that the `aioConfig_s[i].uHeader.sHeaderTyp1.bitAddress` field is necessary to find the `SAioConfig` for a given address. Maybe use a separate `u8[]` array to store the address for a given array index?

2022-11-21 16:03 UTC, linosanfilippo-kunbus commented on piAIOComm.c
> -			if (piIoComm_response_valid(&sResponse_l, i8uAddress, len_l)) {
It was by intention to not return an error for this case. The usual API for receiving any kind of (network) messages just requests a buffer that is large enough to store the received data and the buffer length. It usually is not an error if the provided buffer is larger than necessary. I find the (re)interpretation of "buffer length" as "expected length" rather strange. And even though this was the logic implemented in piControl I dont think that we necessarily have to overtake it for the new serdev API...

2022-11-22 18:06 UTC, l1k requested changes

2022-11-22 19:04 UTC, linosanfilippo-kunbus commented on piAIOComm.c
> +			      AIO_CONFIG_DATA2_LEN, NULL, 0);
In this function snd_buf is admittedly not as helpful as in piAIOComm_sendCyclicTelegram(). But I would like to keep it, to have a certain consistency across both functions.

2022-11-22 19:14 UTC, linosanfilippo-kunbus commented on piAIOComm.c
> +			addr, ret);
hmm, this is the same indentation that we also use in pibridge.c

2022-11-25 08:46 UTC, l1k approved these changes

2022-11-25 09:13 UTC, merged