Cleanup debianization
RevolutionPi/piControl pull request #84
Opened 2023-03-13 16:02 UTC by nbuchwitz

This is a minimal cleanup patch for the debianization of pitest. Yes this will be redone at a later stage, but let's fix what we can do right now with little to no effort.

2023-03-13 16:36 UTC, naruxde requested changes

2023-03-13 16:36 UTC, naruxde commented on debian/copyright
>   This package is free software; you can redistribute it and/or modify
```suggestion
Copyright: 2016-2023 Kunbus GmbH
License: GPL-2.0+

 Files: debian/*
 Copyright: 2016-2023 KUNBUS GmbH
 License: GPL-2.0+

License: GPL-2.0+
 This package is free software; you can redistribute it and/or modify
```

Just to follow our defaults ;)

2023-03-13 16:45 UTC, naruxde submitted a review, later dismissed

2023-03-16 11:13 UTC, naruxde approved these changes

2023-03-16 11:39 UTC, RamiGspo approved these changes
LGTM

2023-03-16 11:40 UTC, naruxde requested changes

2023-03-16 11:40 UTC, naruxde commented on debian/control
>  Priority: extra
linter: priority-extra-is-replaced-by-priority-optional
```suggestion
Priority: optional
```

2023-03-16 11:44 UTC, naruxde approved these changes

2023-03-16 21:06 UTC, merged