piTest: Add Connect 4 as known device
RevolutionPi/piControl pull request #88
Opened 2023-04-28 09:59 UTC by nbuchwitz

Besides the implementation of the Connect 4 support in piControl, we need to add the device as known in piTest.

2023-04-28 11:24 UTC, linosanfilippo-kunbus approved these changes
Adding a new type "Connect 4" means we have to add a new MODGATECOM_IDResp struct in RevPiDevice.c to support this. Until now we have used the same MODGATECOM_IDResp structure for Connect and Connect SE and the same structure for Core and Core SE. However we could use the same structs for the SE and non-SE models, since the length of the input and output parameters were the same. Since now with Connect 4 the number of input and output parameters have increased, I think its ok to create a new struct for this.

2023-05-01 06:50 UTC, l1k commented
I don't think a `MODGATECOM_IDResp` struct needs to be added just for the userspace support. That struct is only needed internally for the kernel-side code AFAICS. And the struct *is* added on the <a href="https://github.com/nbuchwitz/piControl/commits/connect4">connect4 branch</a> in commit nbuchwitz/piControl@1b93f6c1d6eb5e61001cfe6a81330540cd10109c.

However, this present pull request should add the definition of `KUNBUS_FW_DESCR_TYP_PI_CONNECT_4` in `common_define.h` so that number 136 is reserved and there's no risk of accidentally handing that number out to a different device. Granted, the chance of that happening is low but seems good housekeeping nonetheless.

2023-05-01 06:51 UTC, l1k requested changes
_

2023-05-01 15:14 UTC, nbuchwitz commented
@l1k makes sense. I've added the ID in a separate commit and re-ordered the commits, so the id is defined before it's used in a later commit.

2023-05-01 15:15 UTC, l1k approved these changes
I'd squash the two commits into one, but whatever... ;)

2023-05-01 15:16 UTC, merged